
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 02 13:53:10 CST 2023
//----------------------------------------------------

package programa;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 18;
  public static final int Link = 37;
  public static final int Llave_c = 25;
  public static final int Op_booleano = 21;
  public static final int All = 40;
  public static final int Llave_a = 24;
  public static final int Circ = 31;
  public static final int If = 9;
  public static final int T_dato = 4;
  public static final int Table = 43;
  public static final int Move = 34;
  public static final int Else = 10;
  public static final int Corchete_c = 27;
  public static final int Corchete_a = 26;
  public static final int Index = 33;
  public static final int Rotate = 35;
  public static final int Division = 16;
  public static final int Int = 5;
  public static final int Cadena = 6;
  public static final int Parentesis_c = 23;
  public static final int Parentesis_a = 22;
  public static final int For = 11;
  public static final int P_coma = 41;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Funcion = 39;
  public static final int Linea = 7;
  public static final int Op_atribucion = 19;
  public static final int ERROR = 44;
  public static final int Op_logico = 17;
  public static final int Squa = 29;
  public static final int Identificador = 3;
  public static final int Draw = 38;
  public static final int Resta = 14;
  public static final int Resize = 36;
  public static final int Array = 42;
  public static final int Multiplicacion = 15;
  public static final int Op_incremento = 20;
  public static final int Numero = 2;
  public static final int Suma = 13;
  public static final int Main = 28;
  public static final int Igual = 12;
  public static final int Comillas = 8;
  public static final int Tria = 30;
  public static final int Trazar = 32;
}

